# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:latest
    container_name: product-service-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service-mongo
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}

#  mongo-express:
#    image: mongo-express
#    restart: always
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
#      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/