spring:
  data:
    mongodb:
#      host: localhost:27017
#      port: 27017
#      username: root
#      password: password
#      database: product-service-mongo
#      authentication-database: admin
      uri: mongodb://root:password@localhost:27017/product-service-mongo?authSource=admin

server:
# Specifying the port because we don't want the service ports to conflict
  port: 8080
